# Generated by Django 3.0.3 on 2020-07-29 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='设备名称')),
                ('buy_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='购买时间')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='到期时间')),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
            ],
            options={
                'verbose_name': '设备名称',
                'verbose_name_plural': '设备管理',
            },
        ),
    ]
