# Generated by Django 3.0.3 on 2020-07-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200729_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='', verbose_name='二维码'),
        ),
    ]
