# Generated by Django 3.0.3 on 2020-07-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr_code', verbose_name='二维码'),
        ),
    ]
