# Generated by Django 3.0.3 on 2020-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_map', models.CharField(max_length=128, verbose_name='地点')),
                ('name_map', models.CharField(max_length=128, verbose_name='工程名称')),
                ('type_map_choices', models.IntegerField(choices=[(0, '鄞州公路段'), (1, '海曙公路段'), (2, '江北公路段'), (3, '镇海公路段')], verbose_name='所属项目')),
                ('id_map', models.CharField(max_length=128, verbose_name='点位编号')),
                ('install_map', models.CharField(max_length=128, verbose_name='安装方式')),
                ('install_map_1', models.CharField(max_length=128, verbose_name='安装位置')),
                ('type', models.IntegerField(choices=[(0, '高清球机'), (1, '高清枪机'), (2, '传感器')], verbose_name='所属项目')),
                ('Pixel', models.IntegerField(choices=[(0, '200万'), (1, '300万'), (2, '900万')], verbose_name='像素')),
                ('night', models.IntegerField(choices=[(0, '红外'), (1, '无')], verbose_name='夜视')),
                ('Electrical_type', models.IntegerField(choices=[(0, '民电'), (1, '市政'), (2, '单位'), (3, '供电所'), (4, '太阳能'), (5, '村里用电')], verbose_name='接电类型')),
                ('phone_number_map', models.CharField(max_length=12, verbose_name='联系方式')),
                ('electrical_map', models.CharField(max_length=128, verbose_name='接电位置')),
                ('electrical_max', models.CharField(max_length=128, verbose_name='电源长度')),
                ('net_max', models.CharField(max_length=128, verbose_name='网线长度')),
                ('Carrier_map', models.CharField(max_length=128, verbose_name='运营商链路')),
                ('img', models.ImageField(upload_to='img/%Y/%m/%d', verbose_name='安装环境简易图')),
                ('img1', models.ImageField(upload_to='img/%Y/%m/%d', verbose_name='安装环境照片')),
            ],
        ),
    ]
