# Generated by Django 3.0.3 on 2020-04-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmap', '0002_auto_20200420_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table_view',
            options={'verbose_name': '勘察表', 'verbose_name_plural': '现场勘察信息'},
        ),
        migrations.AlterField(
            model_name='table_view',
            name='type_map_choices',
            field=models.IntegerField(choices=[(0, '鄞州公路段'), (1, '海曙公路段'), (2, '江北公路段'), (3, '镇海公路段')], verbose_name='所属项目'),
        ),
    ]
