# Generated by Django 3.0.3 on 2020-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmap', '0002_auto_20200420_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table_view',
            options={'verbose_name': '勘察表', 'verbose_name_plural': '现场勘察信息'},
        ),
        migrations.AlterField(
            model_name='table_view',
            name='Pixel',
            field=models.IntegerField(blank=True, choices=[(0, '200万'), (1, '300万'), (2, '900万')], default='null', null=True, verbose_name='像素'),
        ),
        migrations.AlterField(
            model_name='table_view',
            name='img',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='img/%Y/%m/%d', verbose_name='安装环境简易图'),
        ),
        migrations.AlterField(
            model_name='table_view',
            name='img1',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='img/%Y/%m/%d', verbose_name='安装环境照片'),
        ),
        migrations.AlterField(
            model_name='table_view',
            name='night',
            field=models.IntegerField(blank=True, choices=[(0, '红外'), (1, '无')], default='null', null=True, verbose_name='夜视'),
        ),
        migrations.AlterField(
            model_name='table_view',
            name='type',
            field=models.IntegerField(choices=[(0, '高清球机'), (1, '高清枪机'), (2, '传感器')], verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='table_view',
            name='type_map_choices',
            field=models.IntegerField(choices=[(0, '鄞州公路段'), (1, '海曙公路段'), (2, '江北公路段'), (3, '镇海公路段')], verbose_name='所属项目'),
        ),
    ]
