# Generated by Django 3.0.3 on 2020-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmap', '0003_auto_20200420_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_view',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='安装环境简易图'),
        ),
        migrations.AlterField(
            model_name='table_view',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='安装环境照片'),
        ),
    ]
