# Generated by Django 3.0.3 on 2020-04-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmap', '0004_auto_20200420_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_view',
            name='img',
            field=models.ImageField(default='', upload_to='img/%Y/%m/%d', verbose_name='安装环境简易图'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table_view',
            name='img1',
            field=models.ImageField(upload_to='img/%Y/%m/%d', verbose_name='安装环境照片'),
        ),
    ]
