# Generated by Django 3.0.3 on 2020-04-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmap', '0005_auto_20200420_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_view',
            name='Pixel',
            field=models.IntegerField(blank=True, choices=[(0, '200万'), (1, '300万'), (2, '900万')], default='null', null=True, verbose_name='像素'),
        ),
        migrations.AlterField(
            model_name='table_view',
            name='img',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='img/%Y/%m/%d', verbose_name='安装环境简易图'),
        ),
        migrations.AlterField(
            model_name='table_view',
            name='img1',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='img/%Y/%m/%d', verbose_name='安装环境照片'),
        ),
        migrations.AlterField(
            model_name='table_view',
            name='night',
            field=models.IntegerField(blank=True, choices=[(0, '红外'), (1, '无')], default='null', null=True, verbose_name='夜视'),
        ),
        migrations.AlterField(
            model_name='table_view',
            name='type',
            field=models.IntegerField(choices=[(0, '高清球机'), (1, '高清枪机'), (2, '传感器')], verbose_name='设备类型'),
        ),
    ]
