# Generated by Django 3.0.3 on 2020-04-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmap', '0003_auto_20200420_1723'),
        ('appmap', '0006_auto_20200420_1721'),
    ]

    operations = [
    ]
