# Generated by Django 3.0.3 on 2020-04-09 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '鄞州公路段'), (1, '海曙公路段'), (2, '江北公路段'), (3, '镇海公路段')], verbose_name='所属项目')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('typename', models.SmallIntegerField(choices=[(0, '死机'), (1, '断电'), (2, '无法ping通'), (3, '无法判断，需要现场查看')], verbose_name='故障类型')),
                ('name', models.CharField(max_length=128, verbose_name='地点')),
                ('money', models.TextField(max_length=128, verbose_name='故障描述')),
                ('solve', models.SmallIntegerField(choices=[(0, '未解决'), (1, '已解决')], default=0, verbose_name='故障类型')),
                ('img', models.ImageField(upload_to='img/%Y/%m/%d', verbose_name='现场照片')),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
            ],
            options={
                'verbose_name': '故障',
                'verbose_name_plural': '故障信息',
            },
        ),
    ]
