# Generated by Django 3.0.3 on 2020-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='solve',
            field=models.SmallIntegerField(choices=[(0, '未解决'), (1, '已解决')], default=0, verbose_name='是否解决'),
        ),
    ]
