# Generated by Django 3.0.3 on 2020-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0002_auto_20200418_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='现场照片'),
        ),
    ]
