# Generated by Django 3.0.3 on 2020-04-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0003_auto_20200420_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
