# Generated by Django 3.0.3 on 2020-04-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0006_auto_20200420_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='img',
            field=models.ImageField(default='', upload_to='img/%Y/%m/%d', verbose_name='现场照片'),
            preserve_default=False,
        ),
    ]
