# Generated by Django 3.0.3 on 2020-04-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0007_auto_20200420_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='img',
            field=models.ImageField(default='null', null=True, upload_to='img/%Y/%m/%d', verbose_name='现场照片'),
        ),
    ]
