# Generated by Django 3.0.3 on 2020-04-20 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finam', '0010_record_user_finam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user_finam',
        ),
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.CharField(default='anonymous', editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='record',
            name='user_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='上报人'),
        ),
    ]
