# Generated by Django 3.0.3 on 2020-04-20 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finam', '0011_auto_20200420_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='上报人'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上报人'),
        ),
    ]
