# Generated by Django 3.0.3 on 2020-04-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0012_auto_20200420_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='author',
        ),
    ]
