# Generated by Django 3.0.3 on 2020-04-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0013_remove_record_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
