# Generated by Django 3.0.3 on 2020-04-21 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0015_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='athorfunam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeathor', models.CharField(max_length=128, verbose_name='所属项目')),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='solve',
            field=models.CharField(choices=[('未解决', '未解决'), ('已解决', '已解决')], default=0, max_length=128, verbose_name='是否解决'),
        ),
        migrations.AlterField(
            model_name='record',
            name='typename',
            field=models.CharField(choices=[('死机', '死机'), ('断电', '断电'), ('无法ping通', '无法ping通'), ('无法判断，需要现场查看', '无法判断，需要现场查看')], max_length=128, verbose_name='故障类型'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finam.athorfunam', verbose_name='所属项目'),
        ),
    ]
