# Generated by Django 3.0.3 on 2020-04-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0016_auto_20200421_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='solve',
            field=models.SmallIntegerField(choices=[(0, '未解决'), (1, '已解决')], default=0, verbose_name='是否解决'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.IntegerField(choices=[(0, '鄞州公路段'), (1, '海曙公路段'), (2, '江北公路段'), (3, '镇海公路段')], verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='record',
            name='typename',
            field=models.SmallIntegerField(choices=[(0, '死机'), (1, '断电'), (2, '无法ping通'), (3, '无法判断，需要现场查看')], verbose_name='故障类型'),
        ),
        migrations.DeleteModel(
            name='athorfunam',
        ),
    ]
