# Generated by Django 3.0.3 on 2020-04-21 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0018_auto_20200421_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finam.athorfunam', verbose_name='所属项目'),
        ),
    ]
