# Generated by Django 3.0.3 on 2020-04-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0019_auto_20200421_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athorfunam',
            old_name='type',
            new_name='type_athor',
        ),
    ]
