# Generated by Django 3.0.3 on 2020-04-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0022_auto_20200421_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugtype',
            old_name='BugName',
            new_name='name',
        ),
    ]
