# Generated by Django 3.0.3 on 2020-04-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0023_auto_20200421_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BugType',
            new_name='BugType1',
        ),
    ]
