# Generated by Django 3.0.3 on 2020-04-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0025_auto_20200421_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugName1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='故障类型名字应该唯一', max_length=128, unique=True, verbose_name='故障类型')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '故障类型',
                'verbose_name_plural': '故障类型管理',
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='typename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finam.BugName1', verbose_name='故障类型'),
        ),
        migrations.DeleteModel(
            name='BugName',
        ),
    ]
