# Generated by Django 3.0.3 on 2020-04-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0026_auto_20200421_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='typename',
        ),
        migrations.DeleteModel(
            name='BugName1',
        ),
    ]
