# Generated by Django 3.0.3 on 2020-04-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0027_auto_20200421_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user_choice',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
