# Generated by Django 3.0.3 on 2020-04-21 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finam', '0028_auto_20200421_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugName1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='故障类型名字应该唯一', max_length=128, unique=True, verbose_name='故障类型')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '故障类型',
                'verbose_name_plural': '故障类型管理',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='所属项目名字应该唯一', max_length=128, unique=True, verbose_name='所属项目')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '所属项目',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('name', models.CharField(max_length=128, verbose_name='地点')),
                ('money', models.TextField(max_length=128, verbose_name='故障描述')),
                ('solve', models.CharField(choices=[('未解决', '未解决'), ('已解决', '已解决')], default=0, max_length=128, verbose_name='是否解决')),
                ('img', models.ImageField(blank=True, default='null', null=True, upload_to='img/%Y/%m/%d', verbose_name='现场照片')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finam.Department', verbose_name='所属项目')),
                ('typename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finam.BugName1', verbose_name='故障类型')),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
            ],
            options={
                'verbose_name': '故障',
                'verbose_name_plural': '故障信息',
            },
        ),
    ]
