# Generated by Django 3.0.3 on 2020-04-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0003_auto_20200420_1723'),
        ('finam', '0029_bugname1_department_record'),
    ]

    operations = [
    ]
