# Generated by Django 3.0.3 on 2020-05-06 01:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0030_merge_20200422_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='点位名称')),
            ],
            options={
                'verbose_name': '点位',
                'verbose_name_plural': '点位管理',
            },
        ),
        migrations.RemoveField(
            model_name='record',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
        migrations.AddField(
            model_name='record',
            name='CREATED_TIME',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='record',
            name='UPDATED_BY',
            field=models.CharField(default='', max_length=32, verbose_name='更新人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='UPDATED_TIME',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='record',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='点位桩号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='img_over',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='img_over/%Y/%m/%d', verbose_name='现场解决照片'),
        ),
        migrations.AlterField(
            model_name='record',
            name='money',
            field=models.TextField(max_length=500, verbose_name='故障描述'),
        ),
        migrations.AddField(
            model_name='record',
            name='provience',
            field=models.ForeignKey(db_column='provience_id', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='finam.AddMap', verbose_name='点位名称'),
            preserve_default=False,
        ),
    ]
