# Generated by Django 3.0.3 on 2020-05-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0031_auto_20200506_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='UPDATED_money',
            field=models.TextField(default='', max_length=500, verbose_name='解决过程描述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='UPDATED_TIME',
            field=models.DateTimeField(verbose_name='解决时间'),
        ),
    ]
