# Generated by Django 3.0.3 on 2020-05-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0032_auto_20200509_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='UPDATED_money',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='解决过程描述'),
        ),
    ]
