# Generated by Django 3.0.3 on 2020-05-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0033_auto_20200509_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devicename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='设备名称')),
            ],
            options={
                'verbose_name': '设备名称',
                'verbose_name_plural': '设备管理',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='device',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='finam.Devicename', verbose_name='设备名称'),
            preserve_default=False,
        ),
    ]
