# Generated by Django 3.0.3 on 2020-05-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0034_auto_20200511_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='UPDATED_TIME',
            field=models.DateTimeField(auto_now_add=True, verbose_name='解决时间'),
        ),
    ]
