# Generated by Django 3.0.3 on 2020-05-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0035_auto_20200511_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='UPDATED_TIME',
            field=models.DateTimeField(blank=True, default='null', null=True, verbose_name='解决时间'),
        ),
    ]
