# Generated by Django 3.0.3 on 2020-05-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0036_auto_20200511_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='img_over',
            field=models.ImageField(blank=True, null=True, upload_to='img_over/%Y/%m/%d', verbose_name='现场解决照片'),
        ),
    ]
