# Generated by Django 3.0.3 on 2020-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0037_auto_20200511_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='UPDATED_TIME',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解决时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='img_over',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='img_over/%Y/%m/%d', verbose_name='现场解决照片'),
        ),
    ]
