# Generated by Django 3.0.3 on 2020-07-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0038_auto_20200511_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='provience',
            field=models.CharField(max_length=200, verbose_name='点位名称'),
        ),
    ]
