# Generated by Django 3.0.3 on 2020-07-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0039_auto_20200709_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='send',
            field=models.CharField(choices=[('不发送', '不发送'), ('发送', '发送')], default=0, max_length=128, verbose_name='是否发送'),
        ),
    ]
