# Generated by Django 3.0.3 on 2020-07-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0040_record_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='send',
        ),
    ]
