# Generated by Django 3.0.3 on 2020-07-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0043_auto_20200715_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/%Y/%m/%d', verbose_name='现场照片'),
        ),
    ]
