# Generated by Django 3.0.3 on 2020-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0044_auto_20200715_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='img_over',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img_over/%Y/%m/%d', verbose_name='现场解决照片'),
        ),
    ]
