# Generated by Django 3.0.3 on 2020-07-17 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0045_auto_20200715_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='CREATED_TIME',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 48, 43, 221303), verbose_name='创建时间'),
        ),
    ]
