# Generated by Django 3.0.3 on 2020-07-17 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0046_auto_20200717_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='CREATED_TIME',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
