# Generated by Django 3.0.3 on 2020-07-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0047_auto_20200717_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='SOLVED_TIME',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解决时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='UPDATED_TIME',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='修改时间'),
        ),
    ]
