# Generated by Django 3.0.3 on 2020-07-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0048_auto_20200717_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='UPDATED_TIME',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
    ]
