# Generated by Django 3.0.3 on 2025-03-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finam', '0039_auto_20200709_1007'),
        ('finam', '0049_auto_20200717_1309'),
    ]

    operations = [
    ]
